# EEG Foundation Challenge 2025 - Challenge 1 Configuration
# Cross-Task Transfer Learning: CCD EEG → CCD Behavioral Outcomes

# Challenge 1 specific settings
challenge1:
  use_sus_eeg: true         # Disable SuS EEG data (X2) by default
  use_demographics: false    # Disable demographics/psychopathology (P) by default
  description: Training with CCD EEG data (X1) to predict CCD behavioral outcomes
  targets:
    response_time:
      type: regression
      min_val: 0.0
      max_val: 2000.0
    hit_miss:
      type: classification
      num_classes: 2
      class_names:
      - miss
      - hit
  evaluation:
    primary_metric: response_time_r2
    secondary_metrics:
    - hit_miss_acc
  cv_folds: 5
  cv_strategy: subject_stratified

# Model configuration
model:
  name: Challenge1Model
  n_channels: 128
  n_times: 512
  hidden_dim: 512
  encoder_type: transformer
  cnn:
    temporal_filters:
    - 64
    - 128
    spatial_filters:
    - 256
    - 256
    kernel_sizes:
    - 25
    - 13
    - 7
    - 3
    dropout: 0.2
  transformer:
    d_model: 512
    nhead: 8
    num_layers: 6
    dropout: 0.1
    patch_size: 16
    activation: gelu
    norm_first: true

# Data configuration
data:
  data_dir: ./data/raw/HBN_BIDS_EEG
  channel_count: 128
  sampling_rate: 256
  preprocessing:
    filter_low: 0.5
    filter_high: 70.0
    resample_freq: 256
    epoch_length: 2.0
  augmentation:
    noise_factor: 0.01
    time_shift: 0.1
    channel_dropout: 0.05
  quality_checks:
    max_bad_channels: 10
    max_amplitude: 200.0
    min_epoch_length: 1.8
    reject_criteria:
      eeg: 200e-6
    interpolate_bad_channels: true
    max_interpolated: 5

# # Quick test mode for development
# quick_test:
#   enabled: true
#   max_subjects: 3
#   bids_dirs:
#   - cmi_bids_R1
#   - cmi_bids_R2

# Quick test mode for development
quick_test:
  enabled: true
  max_subjects: 3
  bids_dirs:
  - cmi_bids_R1

# Training configuration
training:
  learning_rate: 5.0e-05
  weight_decay: 1e-4
  min_lr: 1e-6
  scheduler:
    type: cosine
    warmup_epochs: 10
    warmup_start_lr: 1e-6
  max_epochs: 100
  batch_size: 4
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5
  mixed_precision: true
  loss_weights:
    response_time: 0.5
    hit_miss: 0.5
  response_time_scale: 1.0
  early_stopping:
    patience: 15
    monitor: val/total_loss
    mode: min
    min_delta: 0.001

# Validation configuration
validation:
  val_check_interval: 0.25
  metrics:
  - response_time_r2
  - hit_miss_acc

# Hardware configuration
hardware:
  num_workers: 0
  pin_memory: true
  persistent_workers: true
  precision: 16-mixed
  find_unused_parameters: false
  use_all_gpus: false
  strategy: auto
  cnn_memory_gb: 6
  transformer_memory_gb: 12
  performance:
    efficient_attention: true
    gradient_checkpointing: false
    clear_cache: true

# Logging configuration
logging:
  log_every_n_steps: 10
  save_top_k: 3
  monitor: val/total_loss
  experiment_name: challenge1_per_trial
  project_name: eeg_foundation_challenge
  checkpoint_dir: ./checkpoints/challenge1
  save_last: false
  save_weights_only: false
  save_on_train_epoch_end: false

# Caching configuration
caching:
  enabled: true
  cache_dir: ./cache
  clear_cache: true
  cache_format: pickle

# Parallel processing configuration
parallel:
  enabled: false
  max_workers: 4
  batch_size: 20
  chunk_size: 5

# Reproducibility settings
seed: 42
deterministic: true
benchmark: false

# Architecture comparison settings (for research)
comparison:
  run_both_architectures: false # true
  cnn_config:
    learning_rate: 1e-4
    batch_size: 32
    max_epochs: 80
  transformer_config:
    learning_rate: 5e-4
    batch_size: 16
    max_epochs: 100
    warmup_epochs: 1
